version: 3

dotenv:
  - .envrc

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  replacetokens:
    desc: Replace tokens in config files using environment variables
    env:
      # USERNAME is native on Windows; on Unix fall back to USER
      USERNAME: '{{if .USERNAME}}{{.USERNAME}}{{else}}{{env "USER"}}{{end}}'
    cmds:
      - |
        bunx replacetokens \
          --sources "nushell/.config/nushell/**/*.nu" \
          --token-pattern 'default' \
          --encoding 'utf-8' \
          --use-env \
          --log-level 'info'
        echo "Token replacement completed for environment: {{.env}}"
    silent: true
