version: 3

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  replacetokens:
    desc: Replace tokens in tfvars templates using environment variables
    cmds:
      - direnv allow
      - |
        replacetokens \
          --sources '.' \
          --token-pattern 'default' \
          --encoding 'utf-8' \
          --use-env \
          --log-level 'info'
        echo "Token replacement completed for environment: {{.env}}"
    silent: true
