omarchy-webapp-remove "HEY"
omarchy-webapp-remove "Basecamp"
omarchy-webapp-remove "WhatsApp"
omarchy-webapp-remove "Google Photos"
omarchy-webapp-remove "Google Contacts"
omarchy-webapp-remove "Google Messages"
omarchy-webapp-remove "ChatGPT"
omarchy-webapp-remove "YouTube"
omarchy-webapp-remove "X"
omarchy-webapp-remove "Figma"
