#!/usr/bin/env bash
# =============================================================================
# Interactive Environment Configuration
# =============================================================================
# This script guides users through setting up their environment variables
# interactively before installation.
# =============================================================================

set -euo pipefail

# Get script directory and dotfiles root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Source Unix libraries
source "$DOTFILES_ROOT/_scripts/unix/lib/init.sh"

# =============================================================================
# Functions
# =============================================================================

prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local result

    if [[ -n "$default" ]]; then
        read -p "$prompt [$default]: " result
        echo "${result:-$default}"
    else
        read -p "$prompt: " result
        echo "$result"
    fi
}

prompt_choice() {
    local prompt="$1"
    local default="$2"
    local result

    read -p "$prompt [$default]: " result
    echo "${result:-$default}"
}

create_envrc_file() {
    local user_fullname="$1"
    local user_email="$2"
    local personal_user="$3"
    local pc_type="$4"

    cat > "$HOME/.envrc" << EOF
# =============================================================================
# ENVIRONMENT VARIABLES - Main Configuration
# =============================================================================
# Generated by configure-env-interactive.sh on $(date)
# =============================================================================

# ===== USER CONFIGURATION =====
export USER_FULLNAME="$user_fullname"
export USER_EMAIL="$user_email"
export PERSONAL_USER="$personal_user"

# ===== MACHINE TYPE =====
export PC_TYPE="$pc_type"  # Options: pro | perso

# ===== OPTIONAL VARIABLES =====
# Uncomment and configure as needed:

# AWS
# export AWS_DEFAULT_REGION="us-east-1"

# Kubernetes
# export KUBECONFIG="\$HOME/.kube/config"

# AI Services
# export OPENAI_API_KEY="YOUR_OPENAI_API_KEY"
# export ANTHROPIC_API_KEY="YOUR_ANTHROPIC_API_KEY"

# ===== LOAD PRIVATE VARIABLES =====
# Source private environment variables from ~/.private.envrc if it exists
if [[ -f "\$HOME/.private.envrc" ]]; then
    source "\$HOME/.private.envrc"
fi
EOF

    chmod 600 "$HOME/.envrc"
}

create_private_envrc_file() {
    if [[ -f "$HOME/.private.envrc" ]]; then
        log_info "~/.private.envrc already exists, keeping it"
        return 0
    fi

    cat > "$HOME/.private.envrc" << 'EOF'
# =============================================================================
# PRIVATE ENVIRONMENT VARIABLES (Secrets)
# =============================================================================
# Add your sensitive credentials here (API keys, passwords, tokens)
# This file is automatically loaded by ~/.envrc
#
# IMPORTANT: NEVER commit this file to git!
# =============================================================================

# ===== CLOUD CREDENTIALS =====
# Uncomment and add your credentials:

# AWS
# export AWS_ACCESS_KEY_ID="YOUR_AWS_ACCESS_KEY_ID"
# export AWS_SECRET_ACCESS_KEY="YOUR_AWS_SECRET_ACCESS_KEY"
# export AWS_ACCOUNT_ID="123456789012"

# Azure
# export AZURE_TENANT_ID="YOUR_AZURE_TENANT_ID"
# export AZDO_PERSONAL_ACCESS_TOKEN="YOUR_AZDO_PAT_TOKEN"

# ===== API KEYS & TOKENS =====
# GitHub
# export GITHUB_TOKEN="YOUR_GITHUB_PAT_TOKEN"

# OpenAI
# export OPENAI_API_KEY="YOUR_OPENAI_API_KEY"

# Anthropic Claude
# export ANTHROPIC_API_KEY="YOUR_ANTHROPIC_API_KEY"

# ===== CUSTOM SECRETS =====
# Add your other secrets below
EOF

    chmod 600 "$HOME/.private.envrc"
}

# =============================================================================
# Main
# =============================================================================

main() {
    log_header "Environment Variables Configuration"

    echo ""
    log_info "This wizard will help you configure your environment variables."
    log_info "You can always edit ~/.envrc and ~/.private.envrc later."
    echo ""

    # Check if .envrc already exists
    if [[ -f "$HOME/.envrc" ]]; then
        log_warning "~/.envrc already exists!"
        echo ""
        read -p "Do you want to reconfigure it? [y/N]: " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Keeping existing configuration"
            exit 0
        fi

        # Backup existing file
        local backup="$HOME/.envrc.backup.$(date +%Y%m%d-%H%M%S)"
        mv "$HOME/.envrc" "$backup"
        log_info "Backed up existing .envrc to: $backup"
        echo ""
    fi

    # Get existing git config as defaults
    local default_name=$(git config --global user.name 2>/dev/null || echo "")
    local default_email=$(git config --global user.email 2>/dev/null || echo "")
    local default_user=$(whoami)

    # Prompt for user information
    log_step "User Information"
    echo ""

    local user_fullname=$(prompt_with_default "Enter your full name" "$default_name")
    local user_email=$(prompt_with_default "Enter your email address" "$default_email")
    local personal_user=$(prompt_with_default "Enter your username" "$default_user")

    echo ""
    log_step "Machine Type"
    echo ""
    log_info "Choose your machine type:"
    log_info "  - 'pro' for work/professional machines"
    log_info "  - 'perso' for personal machines"
    echo ""

    local pc_type=$(prompt_choice "Machine type (pro/perso)" "perso")

    # Validate PC type
    if [[ "$pc_type" != "pro" && "$pc_type" != "perso" ]]; then
        log_warning "Invalid choice '$pc_type', defaulting to 'perso'"
        pc_type="perso"
    fi

    # Summary
    echo ""
    log_header "Configuration Summary"
    echo ""
    echo "  Full Name:      $user_fullname"
    echo "  Email:          $user_email"
    echo "  Username:       $personal_user"
    echo "  Machine Type:   $pc_type"
    echo ""

    read -p "Is this correct? [Y/n]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        log_info "Configuration cancelled"
        exit 0
    fi

    # Create files
    echo ""
    log_step "Creating environment files..."

    create_envrc_file "$user_fullname" "$user_email" "$personal_user" "$pc_type"
    log_success "Created ~/.envrc"

    create_private_envrc_file
    log_success "Created ~/.private.envrc (for secrets)"

    # Direnv setup
    echo ""
    if command -v direnv &> /dev/null; then
        log_step "Setting up direnv..."
        direnv allow ~ 2>/dev/null || true
        log_success "Direnv configured"
    else
        log_info "direnv not installed yet (will be installed during setup)"
        log_info "Run 'direnv allow ~' after installation completes"
    fi

    echo ""
    log_success "Environment configuration complete!"
    echo ""
    log_info "Configuration files created:"
    log_info "  • ~/.envrc - Main configuration"
    log_info "  • ~/.private.envrc - Secrets (edit to add API keys, passwords, etc.)"
    echo ""
    log_info "To edit your configuration later:"
    log_info "  nvim ~/.envrc          # Basic config"
    log_info "  nvim ~/.private.envrc  # Secrets"
    echo ""
}

main "$@"
